### ISSUE TITLE
Can't build hatjitsu using docker-compose on ubuntu 20.04

### ISSUE THREAD

**Issue by PauloGDPeixoto** [richarcher/Hatjitsu#31]
The build itself processes without errors, but as soon as docker-compose tries to launch the container I get this error:
```poker_1  | /Hatjitsu/server.js:12
poker_1  | var app = module.exports = express.createServer();
poker_1  |                                    ^
poker_1  | 
poker_1  | TypeError: express.createServer is not a function
poker_1  |     at Object.<anonymous> (/Hatjitsu/server.js:12:36)
poker_1  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
poker_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
poker_1  |     at Module.load (internal/modules/cjs/loader.js:928:32)
poker_1  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
poker_1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
poker_1  |     at internal/main/run_main_module.js:17:47
hatjitsu_poker_1 exited with code 1
```

**Comment by jlagerweij** [comment]
I had the same problem and created a PR to fix the code again so it works with the new dependabot dependencies.
See this PR: https://github.com/richarcher/Hatjitsu/pull/30

**Comment by PauloGDPeixoto** [comment]
> I had the same problem and created a PR to fix the code again so it works with the new dependabot dependencies.
> See this PR: #30

I worked around this issue precisely by using your `dependency-upgrades`branch :)
