### ISSUE TITLE
Can't run hatjitsu using README instructions

### ISSUE THREAD

**Issue by smyrman** [richarcher/Hatjitsu#8]
First installed npm & nodejs. Latest try was with:

    % node -v
    v0.12.0
    % npm -v
    2.5.1

Try 1 (from Git root):

    npm install -d
    node app

Result 1:

    module.js:338
        throw err;
              ^
    Error: Cannot find module '/work/hatjit/Hatjitsu/app'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

Try 2 (from Git root):

    npm install -d
    npm start

Result 2:

    sh: 1: server.js: not found

    npm ERR! Linux 3.8.0-44-generic
    npm ERR! argv "/work/hatjit/node-v0.12.0-linux-x64/bin/node" "/work/hatjit/node-v0.12.0-linux-x64/bin/npm" "start"
    npm ERR! node v0.12.0
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE
    npm ERR! hatchetapp.net@0.0.1-82 start: `server.js`
    npm ERR! Exit status 127
    npm ERR! 
    npm ERR! Failed at the hatchetapp.net@0.0.1-82 start script 'server.js'.
    npm ERR! This is most likely a problem with the hatchetapp.net package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     server.js
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls hatchetapp.net
   npm ERR! There is likely additional logging output above.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /work/hatjit/Hatjitsu/npm-debug.log

The later error is very weird, because server.js clearly exists in the PWD...

Log file from npm-start:

    0 info it worked if it ends with ok
    1 verbose cli [ '/work/hatjit/node-v0.12.0-linux-x64/bin/node',
    1 verbose cli   '/work/hatjit/node-v0.12.0-linux-x64/bin/npm',
    1 verbose cli   'start',
    1 verbose cli   '/work/hatjit/Hatjitsu' ]
    2 info using npm@2.5.1
    3 info using node@v0.12.0
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info prestart hatchetapp.net@0.0.1-82
    6 info start hatchetapp.net@0.0.1-82
    7 verbose unsafe-perm in lifecycle true
    8 info hatchetapp.net@0.0.1-82 Failed to exec start script
    9 verbose stack Error: hatchetapp.net@0.0.1-82 start: `server.js /work/hatjit/Hatjitsu`
    9 verbose stack Exit status 127
    9 verbose stack     at EventEmitter.<anonymous> (/work/hatjit/node-v0.12.0-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
    9 verbose stack     at EventEmitter.emit (events.js:110:17)
    9 verbose stack     at ChildProcess.<anonymous> (/work/hatjit/node-v0.12.0-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:14:12)
    9 verbose stack     at ChildProcess.emit (events.js:110:17)
    9 verbose stack     at maybeClose (child_process.js:1008:16)
    9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
    10 verbose pkgid hatchetapp.net@0.0.1-82
    11 verbose cwd /work/hatjit/Hatjitsu
    12 error Linux 3.8.0-44-generic
    13 error argv "/work/hatjit/node-v0.12.0-linux-x64/bin/node" "/work/hatjit/node-v0.12.0-linux-x64/bin/npm" "start" "/work/hatjit/Hatjitsu"
    14 error node v0.12.0
    15 error npm  v2.5.1
    16 error code ELIFECYCLE
    17 error hatchetapp.net@0.0.1-82 start: `server.js /work/hatjit/Hatjitsu`
    17 error Exit status 127
    18 error Failed at the hatchetapp.net@0.0.1-82 start script 'server.js /work/hatjit/Hatjitsu'.
    18 error This is most likely a problem with the hatchetapp.net package,
    18 error not with npm itself.
    18 error Tell the author that this fails on your system:
    18 error     server.js /work/hatjit/Hatjitsu
    18 error You can get their info via:
    18 error     npm owner ls hatchetapp.net
    18 error There is likely additional logging output above.
    19 verbose exit [ 1, true ]

Also, http://hat.jit.su/ seems to be down.

**Comment by smyrman** [comment]
This seems to be solved by:
https://github.com/d48/Hatjitsu/commit/2051697869cf2ede6ecce3acbdffcac0dceb03f3

**Comment by d48** [comment]
@smyrman yeah, the commands just needed some updating. you can run it like using the npm convention how I have it in the pull request or straight with `node server.js`

**Comment by ljharb** [comment]
In addition to `node app` not making *any* sense when you have an app directory and not `app.js`, your `start` script is also broken. It should be `node server.js` not just `server.js`.

After this is fixed, the README should tell people to do `npm start`.

**Comment by d48** [comment]
here you go: https://github.com/richarcher/Hatjitsu/pull/7
